// krewcli-opencode-plugin — auto-generated by krewcli onboard
// Ported from vibe-island/dump/embedded-js/claude-opencode-hook.js
// (the only embedded JS adapter we have full source for).
//
// Subscribes to opencode's internal event bus, normalizes events
// to the canonical hook protocol, and POSTs them to krewhub via
// `/api/v1/tasks/{task_id}/events` (falling back to /hooks/ingest
// when no task is bound).
//
// Differences from vibe-island's original:
//  - HTTP instead of unix domain socket
//  - No permission held-connection (we run --full-auto)
//  - No OSC-2 tab title bits (server-side audit log only)
//  - No tty walking (krewcli bridge env_collector handles that
//    when it forwards from the CLI; opencode plugin runs inside
//    the opencode process and inherits its env directly)

const KREWHUB_URL = (process.env.KREWHUB_URL || "http://127.0.0.1:8420").replace(/\/$/, "");
const API_KEY = process.env.KREWHUB_API_KEY || "dev-api-key";
const TASK_ID = process.env.KREWHUB_TASK_ID || "";
const RECIPE_ID = process.env.KREWHUB_RECIPE_ID || "";
const BUNDLE_ID = process.env.KREWHUB_BUNDLE_ID || "";
const AGENT_ID = process.env.KREWHUB_AGENT_ID || "opencode@hook";

const ENV_KEYS = [
  "TERM_PROGRAM", "ITERM_SESSION_ID", "TERM_SESSION_ID",
  "TMUX", "TMUX_PANE", "KITTY_WINDOW_ID", "__CFBundleIdentifier",
  "CONDUCTOR_WORKSPACE_NAME", "CONDUCTOR_PORT", "CURSOR_TRACE_ID",
  "CMUX_WORKSPACE_ID", "CMUX_SURFACE_ID", "CMUX_SOCKET_PATH",
];

function collectEnv() {
  const out = {};
  for (const k of ENV_KEYS) if (process.env[k]) out[k] = process.env[k];
  return out;
}

const HOOK_TO_KREWHUB_TYPE = {
  SessionStart: "session_start",
  SessionEnd: "session_end",
  Stop: "session_end",
  PreToolUse: "tool_use",
  PostToolUse: "tool_use",
  PostToolUseFailure: "tool_use",
  PermissionRequest: "tool_use",
  UserPromptSubmit: "prompt",
  Notification: "agent_reply",
};

function eventBody(payload) {
  const name = payload.hook_event_name;
  const tool = payload.tool_name || "";
  const inp = payload.tool_input || {};
  if (name === "PreToolUse" || name === "PostToolUse" || name === "PostToolUseFailure") {
    const target = inp.file_path || inp.command || inp.path || inp.query || inp.pattern || "";
    const suffix = name === "PostToolUse" ? " ✓" : name === "PostToolUseFailure" ? " ✗" : "";
    return target ? `${tool}(${target})${suffix}` : `${tool}${suffix}`;
  }
  if (name === "SessionStart") return `session_start session=${(payload.session_id || "").slice(0, 12)} cwd=${payload.cwd || ""}`;
  if (name === "Stop" || name === "SessionEnd") return `session_end session=${(payload.session_id || "").slice(0, 12)}`;
  if (name === "UserPromptSubmit") return (payload.prompt || "").slice(0, 200);
  return name;
}

async function forward(payload) {
  const url = TASK_ID
    ? `${KREWHUB_URL}/api/v1/tasks/${TASK_ID}/events`
    : `${KREWHUB_URL}/api/v1/hooks/ingest`;

  const body = TASK_ID
    ? {
        type: HOOK_TO_KREWHUB_TYPE[payload.hook_event_name] || "tool_use",
        actor_id: AGENT_ID,
        actor_type: "hook",
        body: eventBody(payload).slice(0, 240),
        facts: [],
        code_refs: [],
        payload,
      }
    : {
        hook_event_name: payload.hook_event_name,
        task_id: TASK_ID || null,
        bundle_id: BUNDLE_ID || null,
        recipe_id: RECIPE_ID || null,
        agent_id: AGENT_ID,
        session_id: payload.session_id,
        cwd: payload.cwd,
        payload,
      };

  try {
    await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json", "X-API-Key": API_KEY },
      body: JSON.stringify(body),
    });
  } catch (err) {
    // Never block the agent.
  }
}

const TOOL_NAME_MAP = {
  bash: "Bash", read: "Read", edit: "Edit", write: "Write",
  grep: "Grep", glob: "Glob", webfetch: "WebFetch", websearch: "WebSearch",
  task: "Task", todowrite: "TodoWrite",
};

function canonicalTool(raw) {
  if (!raw) return "";
  return TOOL_NAME_MAP[raw.toLowerCase()] || raw;
}

export default async ({ client, serverUrl }) => {
  const pid = process.pid;
  const sessionCwd = new Map();
  const sessions = new Map();

  function getSession(sid) {
    if (!sessions.has(sid)) sessions.set(sid, { lastUserText: "", lastAssistantText: "" });
    return sessions.get(sid);
  }

  function base(sessionId, extra) {
    return {
      session_id: sessionId,
      _source: "opencode",
      _ppid: pid,
      _env: collectEnv(),
      _server_port: serverUrl ? parseInt(serverUrl.port) || 4096 : 4096,
      ...extra,
    };
  }

  function mapEvent(ev) {
    const t = ev.type;
    const p = ev.properties || {};

    if (t === "session.created" && p.info) {
      const cwd = p.info.directory || "";
      sessionCwd.set(p.info.id, cwd);
      return base(`opencode-${p.info.id}`, { hook_event_name: "SessionStart", cwd });
    }
    if (t === "session.deleted" && p.info) {
      sessions.delete(p.info.id);
      sessionCwd.delete(p.info.id);
      return base(`opencode-${p.info.id}`, { hook_event_name: "SessionEnd" });
    }
    if (t === "session.updated" && p.info) {
      if (p.info.directory) sessionCwd.set(p.info.id, p.info.directory);
      if (p.info.time?.archived) {
        sessions.delete(p.info.id);
        sessionCwd.delete(p.info.id);
        return base(`opencode-${p.info.id}`, { hook_event_name: "SessionEnd" });
      }
      return null;
    }
    if (t === "session.status" && p.sessionID) {
      const sid = `opencode-${p.sessionID}`;
      const s = getSession(p.sessionID);
      const cwd = sessionCwd.get(p.sessionID);
      if (p.status?.type === "idle") {
        return base(sid, {
          hook_event_name: "Stop",
          cwd,
          last_assistant_message: s.lastAssistantText || undefined,
        });
      }
    }
    if (t === "message.part.updated" && p.part?.type === "text" && p.part?.messageID) {
      // We don't track message roles here (vibe-island uses a separate
      // message.updated map). Forward only user prompts on a best-effort basis.
      return null;
    }
    if (t === "message.part.updated" && p.part?.type === "tool" && p.part?.sessionID) {
      const sid = `opencode-${p.part.sessionID}`;
      const st = p.part.state?.status;
      const cwd = sessionCwd.get(p.part.sessionID);
      const toolName = canonicalTool(p.part.tool || "");
      if (st === "running" || st === "pending") {
        return base(sid, {
          hook_event_name: "PreToolUse",
          cwd,
          tool_name: toolName,
          tool_input: p.part.state?.input || {},
        });
      }
      if (st === "completed" || st === "error") {
        return base(sid, {
          hook_event_name: st === "error" ? "PostToolUseFailure" : "PostToolUse",
          cwd,
          tool_name: toolName,
        });
      }
    }
    return null;
  }

  return {
    event: async ({ event }) => {
      const mapped = mapEvent(event);
      if (!mapped) return;
      await forward(mapped);
    },
  };
};
