"""Codex CLI hook config writer.

Codex's hook system:
- Gated by `[features] codex_hooks = true` in `<CODEX_HOME>/config.toml`
  (the feature is `under development` but already `true` upstream).
- Hook entries live in `<CODEX_HOME>/hooks.json`.
- Event vocabulary matches Claude's canonical names — `SessionStart`,
  `Stop`, `UserPromptSubmit`, etc. (confirmed against a real
  vibe-island-installed `~/.codex/hooks.json`, not `hook-session-start`
  as the reverse-engineered bridge strings suggested).
- hooks.json schema is the NESTED claude shape:
    { "hooks": { "SessionStart": [ { "hooks": [
        { "type": "command", "command": "...", "timeout": 5 }
      ] } ] } }
- Codex reads config from `$CODEX_HOME` (defaults to `~/.codex`), so we
  can isolate hooks to a workspace dir without touching the user's
  global config by exporting `CODEX_HOME=<workspace>/.codex` when
  spawning the agent.

Codex only fires a subset of events today (SessionStart, Stop,
UserPromptSubmit — no PreToolUse/PostToolUse yet). We still wire the
full canonical set so we get free coverage if codex adds more later.
"""

from __future__ import annotations

import json
import logging
import shutil
from pathlib import Path

from krewcli.hooks.types import HookWiring

logger = logging.getLogger(__name__)

# Canonical names — same vocabulary as claude. Codex matches this set.
_CODEX_HOOK_EVENTS = (
    "SessionStart",
    "UserPromptSubmit",
    "PreToolUse",
    "PostToolUse",
    "Stop",
)


def write(workspace_dir: str) -> HookWiring:
    krewcli_bin = shutil.which("krewcli") or "krewcli"
    codex_dir = Path(workspace_dir) / ".codex"
    config_toml = codex_dir / "config.toml"
    hooks_json = codex_dir / "hooks.json"

    try:
        codex_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        logger.warning("codex writer: failed to create %s: %s", codex_dir, exc)
        return HookWiring(source="codex", notes=f"mkdir failed: {exc}")

    config_body = (
        "# auto-generated by krewcli — do not edit\n"
        "[features]\n"
        "codex_hooks = true\n"
    )

    hooks: dict[str, list[dict]] = {}
    for event in _CODEX_HOOK_EVENTS:
        hooks[event] = [
            {
                "hooks": [
                    {
                        "type": "command",
                        "command": f"{krewcli_bin} bridge --source codex {event}",
                        "timeout": 5,
                    }
                ]
            }
        ]

    files_written: list[Path] = []
    try:
        config_toml.write_text(config_body)
        files_written.append(config_toml.resolve())
        hooks_json.write_text(json.dumps({"hooks": hooks}, indent=2) + "\n")
        files_written.append(hooks_json.resolve())
    except OSError as exc:
        logger.warning("codex writer: write failed: %s", exc)
        return HookWiring(source="codex", notes=f"write failed: {exc}")

    return HookWiring(
        source="codex",
        settings_file=config_toml.resolve(),
        env={
            # Codex honors $CODEX_HOME as its config dir — this
            # isolates hooks to our workspace without touching
            # the user's global ~/.codex.
            "CODEX_HOME": str(codex_dir.resolve()),
            "KREWCLI_CODEX_CONFIG_FILE": str(config_toml.resolve()),
        },
        files_written=files_written,
        notes="codex_hooks feature flag + nested claude-shape hooks.json",
    )
