"""Factory Droid / Amp / Qoder hook config writer.

Drops a TS plugin file at `<workspace_dir>/amp/plugins/krewcli.ts`
that subscribes to Amp's event bus and forwards events to the
krewcli bridge HTTP endpoint. Mirrors vibe-island's
`vibe-island.ts` plugin (which we don't have full source for).

This is a workspace-local plugin file. The user must symlink it
into `~/.config/amp/plugins/` for Amp to load it (or we can
auto-symlink in onboard later).
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

from krewcli.hooks.types import HookWiring

logger = logging.getLogger(__name__)

PLUGIN_FILENAME = "krewcli.ts"

_PLUGIN_TS = """\
// auto-generated by krewcli — do not edit
// Forwards Amp/Droid hook events to the krewcli bridge.
// Mirror of vibe-island/embedded-js/claude-opencode-hook.js,
// adapted for the Amp plugin contract.

const KREWHUB_URL = process.env.KREWHUB_URL || "http://127.0.0.1:8420";
const API_KEY = process.env.KREWHUB_API_KEY || "dev-api-key";
const TASK_ID = process.env.KREWHUB_TASK_ID || "";

async function forward(event: any) {
  const url = TASK_ID
    ? `${KREWHUB_URL}/api/v1/tasks/${TASK_ID}/events`
    : `${KREWHUB_URL}/api/v1/hooks/ingest`;
  try {
    await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-API-Key": API_KEY,
      },
      body: JSON.stringify(
        TASK_ID
          ? {
              type: "tool_use",
              actor_id: "droid@hook",
              actor_type: "hook",
              body: event.hook_event_name || "",
              payload: { ...event, _source: "droid" },
            }
          : { ...event, _source: "droid" }
      ),
    });
  } catch (err) {
    // never block the agent
  }
}

export default {
  name: "krewcli-bridge",
  events: {
    "*": async (event: any) => {
      await forward({
        hook_event_name: event.type || event.name || "Unknown",
        session_id: event.sessionId || event.session_id || "",
        cwd: event.cwd || process.cwd(),
        tool_name: event.tool || event.tool_name || "",
        tool_input: event.input || event.tool_input || {},
      });
    },
  },
};
"""


def write(workspace_dir: str) -> HookWiring:
    plugin_dir = Path(workspace_dir) / "amp" / "plugins"
    plugin_path = plugin_dir / PLUGIN_FILENAME

    try:
        plugin_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        logger.warning("droid writer: failed to create %s: %s", plugin_dir, exc)
        return HookWiring(source="droid", notes=f"mkdir failed: {exc}")

    try:
        plugin_path.write_text(_PLUGIN_TS)
    except OSError as exc:
        logger.warning("droid writer: write failed: %s", exc)
        return HookWiring(source="droid", notes=f"write failed: {exc}")

    abs_path = plugin_path.resolve()
    return HookWiring(
        source="droid",
        settings_file=abs_path,
        env={"KREWCLI_DROID_PLUGIN_FILE": str(abs_path)},
        files_written=[abs_path],
        notes=(
            f"Symlink to ~/.config/amp/plugins/ for Amp to load: "
            f"ln -sf {abs_path} ~/.config/amp/plugins/{PLUGIN_FILENAME}"
        ),
    )
